### ISSUE TITLE
Kibana wont install

### ISSUE THREAD

**Issue by arkheliel** [wazuh/wazuh-cloudformation#71] opened 2020-08-14 15:11 UTC
I used the YML template directly on AWS CloudFormation. Deployment was successful, but Kibana was not installed.

Branch 3.13.1 used.

Is there another way, or correct way to install the production environment?

**Comment by manuasir** [comment] 2020-08-15 14:43
Hello @arkheliel , 

Sorry for the inconvenience, let us investigate this problem and we'll get back to you ASAP.

Regards

**Comment by manuasir** [comment] 2020-09-21 18:42
Hello @arkheliel ,

Sorry for the late response. Were you able to resolve this? I couldn't reproduce in my environment. Can you please try with our latest release?

**Comment by synacktic** [comment] 2020-09-21 21:07
I had the same issue.
I set the SSHAccessCidr to my own IP, and then the scripts configure that as the only IP allowed for ssh. Since some of the scripts scp from the other machines being created in the 10.0.x.x network, they die because they cannot copy anything.
How should SSHAccessCidr be set to allow the new machines to talk to each other and our own IP to connect?

**Comment by synacktic** [comment] 2020-09-21 21:38
Oh, also I found the wazuh user was hard coded into some scripts, so if SshUsername is not wazuh, there will be issues there too.

**Comment by manuasir** [comment] 2020-10-07 14:20
I updated to the latest version `v3.13.2_7.9.2`, please check using the latest template.
On the other hand, I've just merged #73 and #74 to fix the issues reported by @synacktic. Much appreciated.

Please, open a new ticket if you still face issues.

**Closed by manuasir** 2020-10-07 14:20 UTC
